### ISSUE TITLE
下拉列表中,当选择某些值的时候,将表单中的某些字段移除怎么搞

### ISSUE THREAD

**Issue by jonny77** [hyperf-admin/hyperf-admin#17]
![image](https://user-images.githubusercontent.com/1962170/91120746-f5359a80-e6c8-11ea-856d-ff960e4b5386.png)
如图,当我选择了本地硬盘的时候, accessId等字段不能提交到后端去 怎么搞

**Comment by daodao97** [comment]
你提到的 `不能提交到后端去` 是, 现在的现象, 还是目标期望?

看你的`UI`理解, 应该是选择 本地硬盘时不显示下方的一些控件, 将其隐藏即可, 

更复杂的参见 [表单动态计算](https://hyperf-admin.github.io/hyperf-admin/#/backend/form?id=%e7%bb%84%e4%bb%b6%e8%81%94%e5%8a%a8), 根据条件更改目标字段的 属性即可.
![image](https://user-images.githubusercontent.com/15009280/91127133-2bc6e180-e6d8-11ea-94c3-cb263cdb1c46.png)

**Comment by jonny77** [comment]
> 你提到的 `不能提交到后端去` 是, 现在的现象, 还是目标期望?
> 
> 看你的`UI`理解, 应该是选择 本地硬盘时不显示下方的一些控件, 将其隐藏即可,
> 
> 更复杂的参见 [表单动态计算](https://hyperf-admin.github.io/hyperf-admin/#/backend/form?id=%e7%bb%84%e4%bb%b6%e8%81%94%e5%8a%a8), 根据条件更改目标字段的 属性即可.
> ![image](https://user-images.githubusercontent.com/15009280/91127133-2bc6e180-e6d8-11ea-94c3-cb263cdb1c46.png)

是我的期望. 隐藏功能已经实现了.但是当选择了本地硬盘的时候,有些字段我是不希望提交到后端的

**Comment by daodao97** [comment]
这个现在前端没有过滤, 后端忽略掉这些字段, 比较简单些.
