### ISSUE TITLE
我在后台都关闭了相关的定时 怎么控制台还有 

### ISSUE THREAD

**Issue by jonny77** [hyperf-admin/hyperf-admin#19]
2020-08-25 12:20:00||cron_center||INFO||Crontab dispatcher the 6 time, jobs total 0||[]||[]

如何关闭烦人的logger,我上传一张图片,整个图片的内容都打印到控制台了,你服不服....
autoload/logger.php也删除了 没效果...

**Comment by daodao97** [comment]
你可以选择不安装`hyperf-admin/cron-center`模块

**Comment by jonny77** [comment]
> 你可以选择不安装`hyperf-admin/cron-center`模块

我不是特指cron-center 为什么上传的图片 ,会在控制台以文件流的形式打印出来 .

**Comment by daodao97** [comment]
可以看下源码, 实现非常简单 `vendor/daodao97/src/base-utils/src/Middleware/HttpLogMiddleware.php` 中间件负责打印http请求日志, 至于是否打印完整 `request body` 可以优化, 如果你有更好的方案, 欢迎 PR.
