### ISSUE TITLE
设置唯一的验证后报错了

### ISSUE THREAD

**Issue by jonny77** [hyperf-admin/hyperf-admin#20]
'username|用户名' => [
                    'rule'=>'required|alpha_num|member:unique',
                    'props' => [
                        'size' => 'small',
                        'maxlength' => 20,
                    ],
                ],

BadMethodCallException: Method Hyperf\Validation\Validator::validateMember does not exist. in /Users/Documents/www/HYPERF/hyperf-admin-demo/backend/vendor/hyperf/validation/src/Validator.php:236

**Comment by daodao97** [comment]
系统默认支持的验证项参见 hyperf文档 [validation](https://hyperf.wiki/#/zh-cn/validation?id=%e9%aa%8c%e8%af%81%e8%a7%84%e5%88%99)
