### ISSUE TITLE
task任务无法启动

### ISSUE THREAD

**Issue by cruelwolfking** [hyperf-admin/hyperf-admin#23]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊，为啥自定义的task不能启动呢，不兼容吗

**Comment by cruelwolfking** [comment]
`use Hyperf\Crontab\Crontab;
return [
    // 是否开启定时任务
    'enable' => true,
    (new Crontab())->setName('stay_login_status')->setRule('*/15 * * * * *')->setCallback([App\Task\Robot::class, 'execute'])->setMemo('每15s访问一次保持登陆状态'),
    (new Crontab())->setName('spider_start')->setRule('* * * * * *')->setCallback([App\Task\RobotSpider::class, 'execute'])->setMemo('每s运行一次查看是否到时间执行爬虫'),
];
`

**Comment by cruelwolfking** [comment]
我试了，别的项目都正常运行，就加了你们这个就不行

**Comment by daodao97** [comment]
参见 [CronCenter](https://hyperf-admin.github.io/hyperf-admin/#/backend/components/business/cron-center)

`CronCenter` 的作用就是将写在配置文件里的 `计划任务` 迁移到管理后台, 这样在 改动计划任务(启用禁止/运行规则等)时就不用经历 `改代码->合并->发布` 这样的流程了.

**Comment by cruelwolfking** [comment]
作业必须基于App\Util\CronCenter\ClassJobAbstract, 或App/Util/CronCenter/CommandJobAbstract.php,不要动不动参见文档，文档要是写得好没人提问，自己看这段话，按照这个路径找，能找到这个类吗。

**Comment by cruelwolfking** [comment]
而且你后台得关闭禁止根本没有用，操作了还是要重启才生效。
