### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to make() must be of the type string, array given

### ISSUE THREAD

**Issue by awangdonghong** [hyperf-admin/hyperf-admin#3]
您好，启动框架时总是遇到这个错误

[root@bogon hyperf0622]# php bin/hyperf.php start
Scanning app ...
Scan app completed, took 54.962873458862 milliseconds.
Scanning vendor ...
Scan vendor completed, took 659.46698188782 milliseconds.

Fatal error: Uncaught TypeError: Argument 1 passed to make() must be of the type string, array given, called in /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/logger/src/LoggerFactory.php on line 142 and defined in /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/utils/src/Functions.php:407
Stack trace:
#0 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/logger/src/LoggerFactory.php(142): make(Array, Array)
#1 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/logger/src/LoggerFactory.php(133): Hyperf\Logger\LoggerFactory->handler(Array, Array, Array)
#2 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/logger/src/LoggerFactory.php(55): Hyperf\Logger\LoggerFactory->handlers(Array)
#3 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/logger/src/LoggerFactory.php(71): Hyperf\Logger\LoggerFactory->make('default', 'default')
#4 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/base-utils/src/Log.php(10): Hyperf\Logger\LoggerFactory->get('default', 'default')
#5 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admi in /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/utils/src/Functions.php on line 407

**Comment by daodao97** [comment]
由于 hyperf-admin/base-utils 底层设置了 logger 相关的配置, 
和 项目中 autoload/logger.php 的配置, 存在合并的为数组的问题
需要 rm config/autoload/logger.php 兼容性问题后续会解决
 https://hyperf-admin.github.io/hyperf-admin/#/guide/install
