### ISSUE TITLE
Uncaught Hyperf\Logger\Exception\InvalidConfigException: Logger config[config_center.tick] is not defined

### ISSUE THREAD

**Issue by zonghay** [hyperf-admin/hyperf-admin#31]
按照文档的不走，在初始化项目中删除logger.php配置后，执行php bin/hyperf.php vendor:publish hyperf/translation，报如题所示错误。但是我全局搜了一下代码，并没有发现有配置config_center日志的地方
![image](https://user-images.githubusercontent.com/33143889/97278699-0c356c00-1875-11eb-952d-7059f4d0ad67.png)

**Comment by charlesyq** [comment]
遇到同样的问题，请问如何解决

**Comment by daodao97** [comment]
未能复现, 检查下 hyperf-admin 是否为最新版本, 或提供下详细的复现路径 及 环境信息
