### ISSUE TITLE
base-utils 和 HyperfAdmin 中的中间件重复 导致外部 app下配置文件的中间件不起作用

### ISSUE THREAD

**Issue by ban-shi-yi-sheng** [hyperf-admin/hyperf-admin#35]
/hyperf-admin/src/admin/src/ConfigProvider.php
![image](https://user-images.githubusercontent.com/28346321/99211180-bcf2b380-2802-11eb-888c-306f2e2a3970.png)
hyperf-admin/src/base-utils/src/ConfigProvider.php
![image](https://user-images.githubusercontent.com/28346321/99211210-cd0a9300-2802-11eb-8624-7802cfc207b8.png)

**Comment by daodao97** [comment]
fixed!
https://github.com/hyperf-admin/hyperf-admin/blob/c23f8812f86b7fcf178bbca1a53a6e08a2b0f581/src/base-utils/src/classmap/ProviderConfig.php#L79
