### ISSUE TITLE
remote module远程模块Guzzle代理转发时缺少Content-Type

### ISSUE THREAD

**Issue by jyiL** [hyperf-admin/hyperf-admin#38]
HyperfAdmin\BaseUtils\Guzzle的proxy方法

**Comment by daodao97** [comment]
Proxy中有对header的处理, 如果有 Content-type, 应该会原样保留
具体见代码: 
https://github.com/hyperf-admin/hyperf-admin/blob/fbe76a4be3dc9852eba5b0ce3723f3aa319003c0/src/base-utils/src/Guzzle.php#L95

**Comment by daodao97** [comment]
确认了问题, hyperf 会把header 处理成全小写, proxy是 应该在转换成首字母大写

fixed at
https://github.com/hyperf-admin/hyperf-admin/blob/9e1bff08fb2b7df05d7cfcce9c4df0e3f14c0c47/src/base-utils/src/Guzzle.php#L99
