### ISSUE TITLE
登录时报错

### ISSUE THREAD

**Issue by awangdonghong** [hyperf-admin/hyperf-admin#4]
您好，我安装成功前后台，使用前端地址 http://192.168.234.129:9528/  访问，
随后我使用admin/admin 登录，报以下错误

2020-06-19 19:00:47||default||ERROR||#0 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(120): Hyperf\Translation\FileLoader->__construct(Object(Hyperf\Utils\Filesystem\Filesystem), NULL)
#1 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(75): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#2 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(59): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#3 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(195): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#4 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(90): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#5 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/utils/src/Functions.php(412): Hyperf\Di\Container->make('Hyperf\\Translat...', Array)
#6 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/translation/src/FileLoaderFactory.php(26): make('Hyperf\\Translat...', Array)
#7 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/FactoryResolver.php(56): Hyperf\Translation\FileLoaderFactory->__invoke(Object(Hyperf\Di\Container))
#8 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(59): Hyperf\Di\Resolver\FactoryResolver->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#9 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(195): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#10 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(90): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#11 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(125): Hyperf\Di\Container->make('Hyperf\\Contract...')
#12 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/translation/src/TranslatorFactory.php(30): Hyperf\Di\Container->get('Hyperf\\Contract...')
#13 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/FactoryResolver.php(56): Hyperf\Translation\TranslatorFactory->__invoke(Object(Hyperf\Di\Container))
#14 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(59): Hyperf\Di\Resolver\FactoryResolver->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#15 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(195): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#16 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(90): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#17 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(125): Hyperf\Di\Container->make('Hyperf\\Contract...')
#18 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Definition/Reference.php(73): Hyperf\Di\Container->get('Hyperf\\Contract...')
#19 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(55): Hyperf\Di\Definition\Reference->resolve(Object(Hyperf\Di\Container))
#20 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ParameterResolver.php(68): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\Reference))
#21 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(119): Hyperf\Di\Resolver\ParameterResolver->resolveParameters(Object(Hyperf\Di\Definition\MethodInjection), Object(ReflectionMethod), Array)
#22 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(75): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#23 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(59): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#24 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(195): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#25 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(90): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#26 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/utils/src/Functions.php(412): Hyperf\Di\Container->make('Hyperf\\Validati...', Array)
#27 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/validation/src/Validation.php(19): make('Hyperf\\Validati...')
#28 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(120): HyperfAdmin\Validation\Validation->__construct()
#29 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(75): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#30 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(59): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#31 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(195): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#32 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(90): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#33 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/utils/src/Functions.php(412): Hyperf\Di\Container->make('HyperfAdmin\\Val...', Array)
#34 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/base-utils/src/Scaffold/Controller/Controller.php(75): make('HyperfAdmin\\Val...')
#35 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/admin/src/Controller/AdminAbstractController.php(33): HyperfAdmin\BaseUtils\Scaffold\Controller\Controller->__construct(Object(Hyperf\Di\Container), Object(Hyperf\HttpServer\Request), Object(Hyperf\HttpServer\Response))
#36 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(120): HyperfAdmin\Admin\Controller\AdminAbstractController->__construct(Object(Hyperf\Di\Container), Object(Hyperf\HttpServer\Request), Object(Hyperf\HttpServer\Response))
#37 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ObjectResolver.php(75): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#38 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(59): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#39 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(195): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#40 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(90): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#41 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/di/src/Container.php(125): Hyperf\Di\Container->make('HyperfAdmin\\Adm...')
#42 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/base-utils/src/Helper/common.php(382): Hyperf\Di\Container->get('HyperfAdmin\\Adm...')
#43 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/admin/src/Service/PermissionService.php(334): container('HyperfAdmin\\Adm...')
#44 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/admin/src/Middleware/PermissionMiddleware.php(97): HyperfAdmin\Admin\Service\PermissionService->isOpen('/user/login', 'POST')
#45 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): HyperfAdmin\Admin\Middleware\PermissionMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#46 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#47 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/admin/src/Middleware/AuthMiddleware.php(52): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#48 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): HyperfAdmin\Admin\Middleware\AuthMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#49 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#50 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf-admin/hyperf-admin/src/base-utils/src/Middleware/CorsMiddleware.php(23): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#51 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): HyperfAdmin\BaseUtils\Middleware\CorsMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#52 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#53 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/dispatcher/src/HttpDispatcher.php(42): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#54 /tmp/hyperf-admin-0622/hyperf0622/vendor/hyperf/http-server/src/Server.php(113): Hyperf\Dispatcher\HttpDispatcher->dispatch(Object(Hyperf\HttpMessage\Server\Request), Array, Object(Hyperf\HttpServer\CoreMiddleware))
#55 {main}||[]||[]

**Comment by daodao97** [comment]
`hyperf-admin` 依赖于 `hyperf/validation` 组件, 所以需要发布下验证器的依赖文件
```shell
php bin/hyperf.php vendor:publish hyperf/translation
php bin/hyperf.php vendor:publish hyperf/validation
```
详细安装流程:  https://hyperf-admin.github.io/hyperf-admin/#/guide/install
