### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by brianbi** [hyperf-admin/hyperf-admin#47]
composer require hyperf-admin/hyperf-admin
Using version ^0.2.1 for hyperf-admin/hyperf-admin
./composer.json has been updated
Running composer update hyperf-admin/hyperf-admin
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - endclothing/prometheus_client_php dev-master requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but the package is fixed to 7.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - endclothing/prometheus_client_php[v1.0.0, ..., 1.0.1] require guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.x-dev] but the package is fixed to 7.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - hyperf-admin/hyperf-admin 0.2.1 requires hyperf/metric ~2.1.0 -> satisfiable by hyperf/metric[v2.1.0-beta1, ..., 2.1.x-dev (alias of dev-master)].
    - hyperf/metric 2.1.x-dev is an alias of hyperf/metric dev-master and thus requires it to be installed too.
    - hyperf/metric[dev-master, v2.1.0-beta1, ..., 2.1.x-dev] require endclothing/prometheus_client_php ^1.0 -> satisfiable by endclothing/prometheus_client_php[v1.0.0, 1.0.1, 1.0.x-dev (alias of dev-master)].
    - endclothing/prometheus_client_php 1.0.x-dev is an alias of endclothing/prometheus_client_php dev-master and thus requires it to be installed too.
    - Root composer.json requires hyperf-admin/hyperf-admin ^0.2.1 -> satisfiable by hyperf-admin/hyperf-admin[0.2.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
![Uploading QQ截图20210205182635.png…]()

**Comment by daodao97** [comment]
https://hyperf-admin.github.io/hyperf-admin/#/guide/install?id=_5-安装hyperf-admin扩展包
