### ISSUE TITLE
后端启动报错

### ISSUE THREAD

**Issue by 0605** [hyperf-admin/hyperf-admin#49]
**报错信息如图：**
![1616484139427](https://user-images.githubusercontent.com/2875139/112108789-a6fb6200-8beb-11eb-893a-c4be63cea7ac.jpg)

**运行环境：**
docker run --name hyperf-admin \
-v /path/xxx:/data \
-p 9501:9501 -it \
-d \
hyperf/hyperf:7.4-alpine-v3.11-swoole

**安装步骤：**
http://daodao97.gitee.io/hyperf-admin/#/guide/install?id=%e5%90%8e%e7%ab%af%e7%9a%84%e5%ae%89%e8%a3%85

**composer watch  和  php bin/hyperf.php start   启动都报同样的错误**

**错误文字版：**

2021-03-23 07:17:00||default||ERROR||Hyperf\Metric\Exception\InvalidArgumentException: Unsupported Prometheus mode encountered(0) in /data/hyperf-admin/vendor/hyperf/metric/src/Adapter/Prometheus/MetricFactory.php:117
Stack trace:
#0 /data/hyperf-admin/vendor/hyperf/metric/src/Process/MetricProcess.php(53): Hyperf\Metric\Adapter\Prometheus\MetricFactory->handle()
#1 /data/hyperf-admin/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\Metric\Process\MetricProcess->handle()
#2 {main}||[]||[]

**Comment by daodao97** [comment]
在 `"hyperf-admin/hyperf-admin": "^0.2.1"` 版本下未复现上述错误, 检查下`hyperf-admin` 的版本看看

看上面的错误信息 应该是跟 `metrics` 有关, 试试添加以下配置, 关闭`metrics`统计进程

```php
  'metric' => [
      'use_standalone_process' => false
  ],
```

**Comment by 0605** [comment]
关闭metrics统计进程 就可以了。多谢多谢🙏

补充一下，我的机子是Macbook pro M1。docker是 https://docs.docker.com/docker-for-mac/apple-m1/
不知道是不是跟这个有关系。🙈

**Comment by daodao97** [comment]
应该不相关，应该是缺少metrics的相关配置导致进程机场，如果后续需要统计信息还是需要开启的，那时要补足对应配置信息
