### ISSUE TITLE
登录提示参数错误

### ISSUE THREAD

**Issue by awangdonghong** [hyperf-admin/hyperf-admin#5]
前端请求接口地址：
http://192.168.234.129:9528/api/user/login
参数：
{"username":"daodao","password":"admin"}
接口返回：
{"code":600,"message":"参数错误","payload":{}}

控制台输出；
2020-06-20 03:22:43||http||INFO||resume||{"referer":"127.0.0.1http://192.168.234.129:9528/system/","uri":"/user/login","request":"{\"username\":\"daodao\",\"password\":\"admin\"}","use_time":8.532047271728516,"response":"{\"code\":600,\"message\":\"参数错误\",\"payload\":{}}"}||[]

**Comment by awangdonghong** [comment]
您好，使用demo里面的daodao用户登录后台，密码是什么？

**Comment by awangdonghong** [comment]
如何可以生成一个后台管理员

**Comment by daodao97** [comment]
如果是运行的 demo 项目 [这里](https://github.com/hyperf-admin/hyperf-admin-demo) , 应该不存在这个问题, 

如果是自己一步步安装的, 请在本地项目里增加 password.salt 的配置, 参见[这里](https://github.com/hyperf-admin/hyperf-admin-demo/blob/master/backend/config/config.php)

**Comment by daodao97** [comment]
系统默认的登录名和密码见[这里](https://hyperf-admin.github.io/hyperf-admin/#/guide/demo)

**Comment by awangdonghong** [comment]
收到，我有把项目跑起来

有推荐么，比如demo和一步步安装选择哪个，或者你更多精力放在哪一个维护上？

**Comment by daodao97** [comment]
重点在 `hyperf-admin/***` 各分包模块上
`demo` 项目在让人于快速了解和提供更多开发样例
两个都会维护. 
更多交流 [这里](https://hyperf-admin.github.io/hyperf-admin/#/guide/communication)
