### ISSUE TITLE
daodao97/hyperf-watch 删除了么？

### ISSUE THREAD

**Issue by tieshengdetie** [hyperf-admin/hyperf-admin#58]
访问404了

**Comment by daodao97** [comment]
是的, 很早期的工具, 现在没什么意义了, 当前请使用官方的 [hyperf/watcher](https://hyperf.wiki/2.2/#/zh-cn/watcher)

**Comment by tieshengdetie** [comment]
可惜了，个人感觉比官方的好用啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperf-admin/hyperf-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hyperf-admin/hyperf-admin] daodao97/hyperf-watch 删除了么？ (Issue #58)





 
是的, 很早期的工具, 现在没什么意义了, 当前请使用官方的 hyperf/watcher
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
