### ISSUE TITLE
前端npm i报错

### ISSUE THREAD

**Issue by nyjah** [hyperf-admin/hyperf-admin#59]
一开始npm i 装不了我用了cnpm install 装到一半 出现  gyp ERR! stack Error: `make` failed with exit code: 2这个问题怎么解决
我的是mac air m1芯片

**Comment by daodao97** [comment]
没有在 m1 下安装过,  不清楚是不是兼容性问题, 其他用户也有 m1 设备下使用的, 没听过反馈, 大概率是网络问题, 找个梯子试试

**Comment by nyjah** [comment]
你好 我前后端已经按照你们的步骤搭建，访问也看到了登陆界面，
但是登陆提交会报502，但是我单独访问后台地址正常返回参数错误，是否是proxy_pass转发有问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperf-admin/hyperf-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月12日(星期六) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hyperf-admin/hyperf-admin] 前端npm i报错 (Issue #59)





 
没有在 m1 下安装过,  不清楚是不是兼容性问题, 其他用户也有 m1 设备下使用的, 没听过反馈, 大概率是网络问题, 找个梯子试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daodao97** [comment]
贴下具体报错

**Comment by nyjah** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperf-admin/hyperf-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月12日(星期六) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hyperf-admin/hyperf-admin] 前端npm i报错 (Issue #59)





 
贴下具体报错
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
