### ISSUE TITLE
怎么将开发迁移到hyperf框架下，而不是在vendor下

### ISSUE THREAD

**Issue by nyjah** [hyperf-admin/hyperf-admin#60]
日常工作开发想在hyperf的app目录下开发，但是现在路由请求都是转发到vendor/hyperf-admin下的controller处理，
附加一个问题：如果权限控制 我想改用casbin，这个框架有办法改造吗

**Comment by daodao97** [comment]
正常的业务开发请参考 [demo](https://github.com/hyperf-admin/hyperf-admin-demo/blob/master/backend/app/Controller/StudentScoreController.php), 除非你需要改动脚手架的基础功能, 如用户管理/角色管理等, 否则, 不牵涉到 `vender` 目录下相关代码的更该, 若实在想改下底层的实现可以 `fork` 本项目.

权限相关的实现在 [PermissionMiddleware](https://github.com/hyperf-admin/hyperf-admin/blob/master/src/admin/src/Middleware/PermissionMiddleware.php), 可以用 DI 替换掉相关实现.

**Comment by nyjah** [comment]
题外话想请教下大佬的对未来php发展的前景如何看法，现在很多项目全跑去java了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刀刀 ***@***.***&gt;
发送时间: 2022年2月14日 09:49
收件人: hyperf-admin/hyperf-admin ***@***.***&gt;
抄送: nyjah ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hyperf-admin/hyperf-admin] 怎么将开发迁移到hyperf框架下，而不是在vendor下 (Issue #60)





 
正常的业务开发请参考 demo, 除非你需要改动脚手架的基础功能, 如用户管理/角色管理等, 否则, 不牵涉到 vender 目录下相关代码的更该, 若实在想改下底层的实现可以 fork 本项目.
 
权限相关的实现在 PermissionMiddleware, 可以用 DI 替换掉相关实现.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daodao97** [comment]
这个话题太大,  不好说, issue 上就不做此类开放问题的讨论, 有兴趣可以在 hyperf 相关微信/QQ群了讨论.
