### ISSUE TITLE
通用表单问题

### ISSUE THREAD

**Issue by v8oo00** [hyperf-admin/hyperf-admin#61]
通用表单修改完某一个表单之后怎么触发后续操作

**Comment by daodao97** [comment]
没明白, 请消息描述下使用场景

**Comment by v8oo00** [comment]
通用表单修改完成后需要删除一下缓存因为在用的时候防止高并发查询数据库，加了一层缓存

**Comment by daodao97** [comment]
可以在后端脚手架的 `afterDelete` 钩子中完成

**Comment by v8oo00** [comment]
重写commonConfig吗

**Comment by daodao97** [comment]
可以 composer classmap 替换 commonConfig 源文件

**Comment by v8oo00** [comment]
好嘞谢谢
