### ISSUE TITLE
Database chartset not set

### ISSUE THREAD

**Issue by jobinli** [hyperf-admin/hyperf-admin#8]
你好，由于config中的 `databases.hyperf_admin` 并没有设置 `charset` 与 `collation` ，会在某些非默认utf8的环境下导致数据库查询乱码，所以觉得应该带上此配置。并且想请问下，`databases.hyperf_admin` 不包含连接池相关配置，那么实际运行中是根据什么配置来定义连接池的呢？

**Comment by daodao97** [comment]
1. 在同一个项目中, `db` 的配置大部分参数是相同的, 所以封装了 `db_complete` 方法, 由其统一补充.
2. 实际项目中, 我们会使用 `config-center` 配置中心, 具体配置每个`db`的连接信息.

**Comment by daodao97** [comment]
`charset` 与 `collation` , `db_complete ` 中没提供, 需要再补充下. 也可以在配置中心里具体配置.

**Comment by daodao97** [comment]
`db_complete` 中已添加 [PR](https://github.com/hyperf-admin/hyperf-admin/commit/75c7488a6d2fb7fd7b5a7d53f8c1ec6fd8441250)
